name: MirrorBot Environment

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  # Change these values if you have forked it for your own works
  GitHubMail: "manofuranium@gmail.com"
  GitHubName: "ElytrA8" 
  BRANCH: "#2"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: setup docker
        run: |
          brew install docker docker-machine virtualbox

      - name: setup vm
        run: |
          docker-machine create -d virtualbox --virtualbox-disk-size "100000" default
          docker-machine env default

      - name: Clone The Secret Mirror Repository
        run: |
          git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.MIRROR_REPOSLUG }} source

      - name: Compile The Mirroring Docker Container
        run: |
          cd source || exit 1
          git checkout $BRANCH
          eval $(docker-machine env default)
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
          docker image ls

      - name: running Docker
        timeout-minutes: 340
        continue-on-error: true
        run: |
          eval $(docker-machine env default)
          docker run --privileged --rm -i mirror-bot

      - name: Loop Workflow
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main

